name: newspaperapp
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  build_runner: ^2.1.7
  connectivity_plus: ^2.2.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_native_splash: 1.3.2
  get: ^4.6.1
  http: ^0.13.4
  intl: ^0.17.0
  line_awesome_flutter: ^2.0.0
  sqfentity: ^2.2.0+1.pre
  sqfentity_gen: ^2.2.0+2.pre
  uuid: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter_native_splash:
  color: "#F5F5FA"
  image: assets/logo/newsapp_logo.png
  color_dark: "#1C1D21"
  image_dark: assets/logo/newsapp_logo.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
  fullscreen: true

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/logo/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Black.ttf
          weight: 900
        - asset: assets/fonts/Lato-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Lato-Thin.ttf
          weight: 100
        - asset: assets/fonts/Lato-ThinItalic.ttf
          style: italic
          weight: 100
